<?php

/*$bebidas= [
    [
        "sabor" => "cola",
        "categoria" => "refrigerante",
        "marca" => "coca-cola"
    ],
    [
        "sabor" => "bluebarry",
        "categoria" => "bebida alcoólica",
        "marca" => "askov"
    ],
    [
        "sabor" => "laranja",
        "categoria" => "suco natural",
        "marca" => "nosliw"
    ],
];

echo $bebidas[1]["marca"];

$lista_frutas=['Banana','Pêra','Tomate','Goiaba'];
$existe=array_search('Banana',$lista_frutas);

if($lista_frutas  != null) {
    echo "O valor existe";
} else {
    echo "O valor não existe";
}

$lista_frutas=['Banana','Pêra','Tomate','Goiaba'];
$existe=in_array('Banana',$lista_frutas);

echo($existe);*/



?>